"""Default AlphaZero hyperparams sections for GUI (alphazero_tree / alphazero_proxy)."""

from __future__ import annotations

AZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "inference_server_enabled",
    "inference_server_mode",
    "num_env_workers",
    "inference_batch_size",
    "inference_batch_interval_ms",
    "inference_timeout",
    "inference_remote_host",
    "inference_remote_port",
    "inference_remote_auth_token",
    "distributed_actors_enabled",
    "distributed_actors_port",
    "distributed_actors_bind_host",
    "distributed_actors_auth_token",
    "distributed_actors_drain_sec",
    "distributed_actors_zmq_hwm",
    "learning_rate",
    "batch_size",
    "value_loss_weight",
    "l2_weight",
    "mcts_simulations",
    "c_puct",
    "dirichlet_alpha",
    "dirichlet_eps",
    "mcts_mode",
    # mcts_candidate_mode / windowed_selfplay / mcts_window_nodes /
    # mcts_joint_action_from_best_child / phase_obs_features / reaction_value_policy
    # вшиты в дефолты (BASE_AZ_TREE_HYPERPARAMS) и убраны из GUI-редактора, чтобы не мешались.
    # Off-switch для legacy остался через env (WINDOWED_SELFPLAY=0, PHASE_OBS_FEATURES=0,
    # AZ_REACTION_VALUE_POLICY=0, MCTS_CANDIDATE_MODE=...) и прямую правку hyperparams.json.
    "mcts_top_k_per_head",
    "mcts_max_depth",
    "mcts_root_dirichlet_only",
    "mcts_batch_eval_size",
    "mcts_parallel_sims",
    "mcts_simulate_enemy",
    "snapshot_opp_deterministic",
    "opponent_stochastic_eps",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "replay_capacity",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "balanced_outcome_sampling",
    "max_policy_staleness_updates",
    "det_eval_gate_win_min",
    "det_eval_gate_turn_limit_max",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
    "mission_bootstrap_coef",
    "hidden_size",
    "num_layers",
    "value_ensemble",
    "lr_scheduler",
    "lr_warmup_steps",
    "lr_total_steps",
    "mcts_eval_cache_size",
    "c_puct_min",
    "c_puct_max",
    "c_puct_schedule",
    "pw_alpha",
    "pw_beta",
    "prior_weight_early",
)

# Не сбрасывать при смене профиля Fast/Balanced/Heavy (LAN / dist; batch size — из пресета).
AZ_INFERENCE_PRESERVE_KEYS: tuple[str, ...] = (
    "inference_server_enabled",
    "inference_server_mode",
    "num_env_workers",
    "inference_batch_interval_ms",
    "inference_timeout",
    "inference_remote_host",
    "inference_remote_port",
    "inference_remote_auth_token",
    "distributed_actors_enabled",
    "distributed_actors_port",
    "distributed_actors_bind_host",
    "distributed_actors_auth_token",
    "distributed_actors_drain_sec",
    "distributed_actors_zmq_hwm",
)

_AZ_BASE: dict[str, int | float | str] = {
    # Inference server (variant B) — по умолчанию выключен до smoke-теста
    "inference_server_enabled": 0,
    "inference_server_mode": "local",
    "num_env_workers": 8,
    "inference_batch_size": 32,
    "inference_batch_interval_ms": 10,
    "inference_timeout": 5.0,
    "inference_remote_host": "127.0.0.1",
    "inference_remote_port": 5555,
    "inference_remote_auth_token": "",
    "distributed_actors_enabled": 0,
    "distributed_actors_port": 5557,
    "distributed_actors_bind_host": "0.0.0.0",
    "distributed_actors_auth_token": "",
    "distributed_actors_drain_sec": 30.0,
    "distributed_actors_zmq_hwm": 256,
    "learning_rate": 0.0003,
    "batch_size": 128,
    "value_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "mcts_simulations": 128,
    "c_puct": 1.1,
    "dirichlet_alpha": 0.3,
    "dirichlet_eps": 0.25,
    "mcts_top_k_per_head": 12,
    "mcts_max_depth": 4,
    "mcts_root_dirichlet_only": 1,
    "snapshot_opp_deterministic": 0,
    "opponent_stochastic_eps": 0.03,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 0.9,
    "temperature_late_value": 0.15,
    "replay_capacity": 200000,
    "num_actors": 8,
    "actor_batch_send": 64,
    "actor_queue_max": 256,
    "sync_every_updates": 2,
    "updates_per_rollout": 2,
    "replay_min_size": 512,
    "balanced_outcome_sampling": 1,
    "max_policy_staleness_updates": 600,
    "det_eval_gate_win_min": 0.45,
    "det_eval_gate_turn_limit_max": 0.65,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
    "mission_bootstrap_coef": 0.0,
    "hidden_size": 256,
    "num_layers": 2,
    "value_ensemble": 1,
    "lr_scheduler": "none",
    "lr_warmup_steps": 0,
    "lr_total_steps": 0,
    "mcts_eval_cache_size": 10000,
    "c_puct_min": 1.0,
    "c_puct_max": 2.0,
    "c_puct_schedule": "none",
    "pw_alpha": 1.0,
    "pw_beta": 0.5,
    "prior_weight_early": 0.25,
    "mcts_batch_eval_size": 16,
    "mcts_parallel_sims": 1,
    "mcts_simulate_enemy": 0,
    "mcts_candidate_mode": "option",
    "windowed_selfplay": 1,
    "mcts_window_nodes": 1,
    "mcts_joint_action_from_best_child": 1,
    "phase_obs_features": 1,
    "reaction_value_policy": 1,
}

# DEFAULT_AZ_TREE_HYPERPARAMS определён ниже как base + balanced-пресет
# (после AZ_TREE_PROFILE_PRESETS), чтобы no-preset дефолт = balanced и не разъезжался.

DEFAULT_AZ_PROXY_HYPERPARAMS: dict[str, int | float | str] = {
    **_AZ_BASE,
    "mcts_mode": "proxy",
    "mcts_simulations": 32,
    "mcts_top_k_per_head": 8,
    "mcts_max_depth": 1,
    "mcts_batch_eval_size": 1,
    "mcts_parallel_sims": 0,
}

AZ_TREE_PROFILE_PRESETS: dict[str, dict[str, int | float]] = {
    "fast": {
        "mcts_simulations": 16,
        "mcts_max_depth": 1,
        "mcts_top_k_per_head": 6,
        "mcts_eval_cache_size": 5000,
        "mcts_batch_eval_size": 8,
        "mcts_parallel_sims": 1,
        "inference_batch_size": 16,
        "mcts_simulate_enemy": 0,
        "num_actors": 8,
        "actor_batch_send": 16,
        "actor_queue_max": 64,
        "batch_size": 64,
        "replay_capacity": 30000,
        "replay_min_size": 256,
        "updates_per_rollout": 1,
        "sync_every_updates": 1,
        "learning_rate": 0.0003,
    },
    "balanced": {
        "mcts_simulations": 32,
        "mcts_max_depth": 1,
        "mcts_top_k_per_head": 10,
        "mcts_eval_cache_size": 10000,
        "mcts_batch_eval_size": 16,
        "mcts_parallel_sims": 4,
        "inference_batch_size": 32,
        "num_actors": 8,
        "actor_batch_send": 32,
        "actor_queue_max": 128,
        "batch_size": 128,
        "replay_capacity": 100000,
        "replay_min_size": 512,
        "updates_per_rollout": 2,
        "sync_every_updates": 2,
        "learning_rate": 0.0003,
    },
    "heavy": {
        "mcts_simulations": 64,
        "mcts_max_depth": 2,
        "mcts_top_k_per_head": 12,
        "mcts_eval_cache_size": 15000,
        "mcts_batch_eval_size": 32,
        "mcts_parallel_sims": 8,
        "inference_batch_size": 64,
        "num_actors": 10,
        "actor_batch_send": 64,
        "actor_queue_max": 256,
        "batch_size": 192,
        "replay_capacity": 250000,
        "replay_min_size": 1024,
        "updates_per_rollout": 2,
        "sync_every_updates": 2,
        "learning_rate": 0.0002,
    },
}

# No-preset дефолт = balanced (чтобы свежий конфиг не был heavy depth=4).
DEFAULT_AZ_TREE_HYPERPARAMS: dict[str, int | float | str] = {
    **_AZ_BASE,
    "mcts_mode": "tree",
    **AZ_TREE_PROFILE_PRESETS["balanced"],
}

AZ_TREE_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "mcts_simulations",
    "mcts_max_depth",
    "mcts_top_k_per_head",
    "num_actors",
    "c_puct",
)

AZ_PROXY_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "num_actors",
    "replay_capacity",
    "updates_per_rollout",
)

AZ_GROUPS: tuple[dict[str, object], ...] = (
    # Inference Server (вариант B) рендерится отдельной панелью AzInferenceServerPanel.qml,
    # поэтому в generic-редакторе группы нет (иначе enabled/mode рисуются спинбоксами).
    {
        "id": "training",
        "title": "Обучение",
        "keys": (
            "learning_rate",
            "batch_size",
            "value_loss_weight",
            "l2_weight",
            "lr_scheduler",
            "lr_warmup_steps",
            "lr_total_steps",
        ),
        "default_collapsed": False,
    },
    {
        "id": "mcts",
        "title": "MCTS",
        "keys": (
            "mcts_mode",
            # mcts_candidate_mode/windowed_selfplay/mcts_window_nodes/mcts_joint_action_from_best_child/
            # phase_obs_features/reaction_value_policy — вшиты в дефолты, скрыты из редактора.
            "mcts_simulations",
            "mcts_max_depth",
            "mcts_top_k_per_head",
            "mcts_root_dirichlet_only",
            "mcts_eval_cache_size",
            "mcts_batch_eval_size",
            "mcts_parallel_sims",
            "mcts_simulate_enemy",
        ),
        "default_collapsed": False,
    },
    {
        "id": "puct",
        "title": "PUCT / exploration",
        "keys": (
            "c_puct",
            "c_puct_min",
            "c_puct_max",
            "c_puct_schedule",
            "dirichlet_alpha",
            "dirichlet_eps",
            "pw_alpha",
            "pw_beta",
            "prior_weight_early",
        ),
        "default_collapsed": True,
    },
    {
        "id": "temperature",
        "title": "Температура",
        "keys": ("temperature_opening_moves", "temperature_opening_value", "temperature_late_value"),
        "default_collapsed": True,
    },
    {
        "id": "actors",
        "title": "Self-play акторы",
        "keys": (
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "updates_per_rollout",
        ),
        "default_collapsed": False,
    },
    {
        "id": "replay_opp",
        "title": "Replay и оппонент",
        "keys": (
            "replay_capacity",
            "replay_min_size",
            "max_policy_staleness_updates",
            "snapshot_opp_deterministic",
            "opponent_stochastic_eps",
            "balanced_outcome_sampling",
        ),
        "default_collapsed": True,
    },
    {
        "id": "outcome_net_eval",
        "title": "Outcome / сеть / DET-eval",
        "keys": (
            "outcome_only",
            "outcome_value_win",
            "outcome_value_loss",
            "outcome_value_draw",
            "mission_bootstrap_coef",
            "hidden_size",
            "num_layers",
            "value_ensemble",
            "det_eval_gate_win_min",
            "det_eval_gate_turn_limit_max",
        ),
        "default_collapsed": True,
    },
)

AZ_FIELD_TOOLTIPS: dict[str, str] = {
    "inference_server_enabled": "1 = вынести net.infer на GPU inference server (вариант B). 0 = текущие CPU акторы (вариант A, по умолчанию).",
    "inference_server_mode": "local = тот же ПК; remote = GPU на ПК2 (ZMQ :5555).",
    "num_env_workers": "Число CPU env-воркеров при inference_server_enabled=1. Рекомендуется = num_actors.",
    "inference_batch_size": "Макс. батч infer-запросов (ПК1). Рекомендуется ≥ num_env_workers × mcts_parallel_sims; balanced≈32, heavy≈64. Remote IS: AZ_REMOTE_BATCH_SIZE на ПК2 ≥ этого значения.",
    "inference_batch_interval_ms": "Окно сбора батча мс (10–20). Меньше = меньше задержка, хуже батчинг.",
    "inference_timeout": "Таймаут ожидания ответа IS (сек). При превышении — retry + лог.",
    "inference_remote_host": "LAN: IP ПК2 с GPU inference server (например 192.168.1.100).",
    "inference_remote_port": "LAN: TCP-порт ПК2 (по умолчанию 5555).",
    "inference_remote_auth_token": "LAN: общий секрет (опционально, должен совпадать с ПК2).",
    "distributed_actors_enabled": "LAN: 1 = доп. env-воркеры на ПК2 (rollout :5557). В GUI включается с LAN по умолчанию.",
    "distributed_actors_port": "LAN: PULL-порт learner для rollout с ПК2 (по умолчанию 5557).",
    "learning_rate": "Скорость обучения policy-value сети.",
    "batch_size": "Размер батча learner.",
    "value_loss_weight": "Вес value loss.",
    "l2_weight": "L2-регуляризация.",
    "mcts_simulations": "Число MCTS-симуляций (важно для Tree).",
    "c_puct": "Коэффициент PUCT.",
    "dirichlet_alpha": "Alpha шума Дирихле в корне.",
    "dirichlet_eps": "Смешивание с prior (eps).",
    "mcts_mode": "tree или proxy (только чтение).",
    "mcts_candidate_mode": (
        "Режим кандидатов корня tree-MCTS: joint (как раньше), filter (joint ∩ легальные планы), "
        "option (окна ActionOption), option_plus (option + legacy greedy). Только при mcts_mode=tree."
    ),
    "windowed_selfplay": (
        "1 = self-play через PhaseEngine (command сейчас; movement/shoot/charge/fight — этап 8.4). "
        "0 = legacy env.step по плоскому action_dict."
    ),
    "mcts_window_nodes": (
        "1 = корень tree-MCTS perturb одного DecisionWindow (command на move 0). "
        "0 = полный turn-plan (option mode). Только при mcts_mode=tree."
    ),
    "mcts_joint_action_from_best_child": (
        "1 = execute coherent joint action from best MCTS child in option/filter mode. "
        "0 = old independent marginal head execution."
    ),
    "phase_obs_features": (
        "1 = добавить в obs +24 dims (фаза one-hot, timing, CP norm, флаги стратагем available/used). "
        "0 = старый размер obs. Меняет размер obs → несовместимо со старыми чекпойнтами (env PHASE_OBS_FEATURES)."
    ),
    "reaction_value_policy": (
        "1 = стратагемы (реакции go to ground/smokescreen/overwatch/heroic + fight + Insane Bravery) "
        "решает net-value 1-ply lookahead с резолвом триггера (дефолт для AZ). "
        "0 = всегда реагировать/legacy. env AZ_REACTION_VALUE_POLICY."
    ),
    "mcts_top_k_per_head": "Top-K действий на голову.",
    "mcts_max_depth": "Глубина rollout в MCTS (Tree).",
    "mcts_root_dirichlet_only": "1 = шум только в корне.",
    "snapshot_opp_deterministic": "1 = снапшот-оппонент детерминированный.",
    "opponent_stochastic_eps": "Epsilon стохастики оппонента.",
    "temperature_opening_moves": "Ходов с opening temperature.",
    "temperature_opening_value": "Температура в дебюте.",
    "temperature_late_value": "Температура в эндшпиле.",
    "replay_capacity": "Ёмкость replay buffer.",
    "num_actors": "Число акторов self-play.",
    "actor_batch_send": "Размер пачки от актора.",
    "actor_queue_max": "Макс. очередь переходов.",
    "sync_every_updates": "Синхронизация весов каждые N updates.",
    "updates_per_rollout": "Updates learner на rollout.",
    "replay_min_size": "Мин. replay до обучения.",
    "max_policy_staleness_updates": "Макс. устаревание политики.",
    "det_eval_gate_win_min": "Порог win rate для gate.",
    "det_eval_gate_turn_limit_max": "Порог turn limit для gate.",
    "outcome_only": "1 = только outcome reward.",
    "outcome_value_win": "Value при победе.",
    "outcome_value_loss": "Value при поражении.",
    "outcome_value_draw": "Value при ничьей.",
    "mission_bootstrap_coef": "Сила mission-bootstrap (0=выкл). Слабый сигнал «играй миссию» по ничьим (контроль точек/HP/VP), не трогая win/loss. Рекомендация: 0.05–0.1.",
    "hidden_size": "Размер скрытого слоя.",
    "num_layers": "Число слоёв.",
    "value_ensemble": "1 = value ensemble.",
    "lr_scheduler": "Планировщик LR.",
    "lr_warmup_steps": "Шаги warmup LR.",
    "lr_total_steps": "Всего шагов для cosine LR.",
    "mcts_eval_cache_size": "Размер кэша eval в MCTS.",
    "c_puct_min": "Мин. c_puct.",
    "c_puct_max": "Макс. c_puct.",
    "c_puct_schedule": "Расписание c_puct.",
    "pw_alpha": "Progressive widening alpha.",
    "pw_beta": "Progressive widening beta.",
    "prior_weight_early": "Вес prior в opening.",
    "balanced_outcome_sampling": "1 = баланс win/loss в replay.",
    "mcts_batch_eval_size": "Размер батча для оценки листьев MCTS (GPU). 1 = отключено, 8-32 = рекомендуется для Tree.",
    "mcts_parallel_sims": "Число параллельных симуляций в MCTS (ThreadPool). 0 = отключено, 4-8 = рекомендуется для Tree.",
    "mcts_simulate_enemy": "1 = ходить за врага в rollout'ах MCTS (точнее, но дороже — enemyTurn самый тяжёлый). 0 = пропустить ход врага, брать оценку сети (быстрее, оценки грубее). Только для Tree.",
}

AZ_PROXY_PROFILE_PRESETS: dict[str, dict[str, int | float]] = {
    "fast": {
        "num_actors": 8,
        "actor_batch_send": 32,
        "actor_queue_max": 128,
        "batch_size": 64,
        "replay_capacity": 50000,
        "replay_min_size": 256,
        "updates_per_rollout": 1,
        "sync_every_updates": 1,
        "learning_rate": 0.0003,
    },
    "balanced": {
        "num_actors": 8,
        "actor_batch_send": 64,
        "actor_queue_max": 256,
        "batch_size": 128,
        "replay_capacity": 200000,
        "replay_min_size": 512,
        "updates_per_rollout": 2,
        "sync_every_updates": 2,
        "learning_rate": 0.0003,
    },
    "heavy": {
        "num_actors": 10,
        "actor_batch_send": 128,
        "actor_queue_max": 512,
        "batch_size": 256,
        "replay_capacity": 500000,
        "replay_min_size": 2048,
        "updates_per_rollout": 3,
        "sync_every_updates": 2,
        "learning_rate": 0.0002,
    },
}

# No-preset дефолт proxy = balanced (tree-дефолт уже = balanced выше).
DEFAULT_AZ_PROXY_HYPERPARAMS = {**DEFAULT_AZ_PROXY_HYPERPARAMS, **AZ_PROXY_PROFILE_PRESETS["balanced"]}
