"""Default AlphaZero hyperparams sections for GUI (alphazero_tree / alphazero_proxy)."""

from __future__ import annotations

AZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "value_loss_weight",
    "l2_weight",
    "mcts_simulations",
    "c_puct",
    "dirichlet_alpha",
    "dirichlet_eps",
    "mcts_mode",
    "mcts_top_k_per_head",
    "mcts_max_depth",
    "mcts_root_dirichlet_only",
    "snapshot_opp_deterministic",
    "opponent_stochastic_eps",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "replay_capacity",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "max_policy_staleness_updates",
    "det_eval_gate_win_min",
    "det_eval_gate_turn_limit_max",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
    "hidden_size",
    "num_layers",
    "value_ensemble",
    "lr_scheduler",
    "lr_warmup_steps",
    "lr_total_steps",
    "mcts_eval_cache_size",
    "c_puct_min",
    "c_puct_max",
    "c_puct_schedule",
    "pw_alpha",
    "pw_beta",
    "prior_weight_early",
)

_AZ_BASE: dict[str, int | float | str] = {
    "learning_rate": 0.0003,
    "batch_size": 128,
    "value_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "mcts_simulations": 128,
    "c_puct": 1.1,
    "dirichlet_alpha": 0.3,
    "dirichlet_eps": 0.25,
    "mcts_top_k_per_head": 12,
    "mcts_max_depth": 4,
    "mcts_root_dirichlet_only": 1,
    "snapshot_opp_deterministic": 0,
    "opponent_stochastic_eps": 0.03,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 0.9,
    "temperature_late_value": 0.15,
    "replay_capacity": 200000,
    "num_actors": 8,
    "actor_batch_send": 64,
    "actor_queue_max": 256,
    "sync_every_updates": 2,
    "updates_per_rollout": 2,
    "replay_min_size": 512,
    "max_policy_staleness_updates": 600,
    "det_eval_gate_win_min": 0.45,
    "det_eval_gate_turn_limit_max": 0.65,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
    "hidden_size": 256,
    "num_layers": 2,
    "value_ensemble": 1,
    "lr_scheduler": "none",
    "lr_warmup_steps": 0,
    "lr_total_steps": 0,
    "mcts_eval_cache_size": 10000,
    "c_puct_min": 1.0,
    "c_puct_max": 2.0,
    "c_puct_schedule": "none",
    "pw_alpha": 1.0,
    "pw_beta": 0.5,
    "prior_weight_early": 0.25,
}

DEFAULT_AZ_TREE_HYPERPARAMS: dict[str, int | float | str] = {
    **_AZ_BASE,
    "mcts_mode": "tree",
    "mcts_simulations": 128,
    "mcts_top_k_per_head": 12,
    "mcts_max_depth": 4,
}

DEFAULT_AZ_PROXY_HYPERPARAMS: dict[str, int | float | str] = {
    **_AZ_BASE,
    "mcts_mode": "proxy",
    "mcts_simulations": 32,
    "mcts_top_k_per_head": 8,
    "mcts_max_depth": 1,
}

AZ_TREE_PROFILE_PRESETS: dict[str, dict[str, int]] = {
    "fast": {"mcts_simulations": 32, "mcts_max_depth": 2, "num_actors": 8},
    "balanced": {"mcts_simulations": 64, "mcts_max_depth": 2, "num_actors": 8},
    "heavy": {"mcts_simulations": 128, "mcts_max_depth": 4, "num_actors": 8},
}

AZ_PROXY_PROFILE_PRESETS: dict[str, dict[str, int]] = {
    "fast": {"mcts_simulations": 16, "mcts_max_depth": 1, "num_actors": 8},
    "balanced": {"mcts_simulations": 32, "mcts_max_depth": 1, "num_actors": 8},
    "heavy": {"mcts_simulations": 64, "mcts_max_depth": 2, "num_actors": 8},
}
