"""Default AlphaZero hyperparams sections for GUI (alphazero_tree / alphazero_proxy)."""

from __future__ import annotations

AZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "value_loss_weight",
    "l2_weight",
    "mcts_simulations",
    "c_puct",
    "dirichlet_alpha",
    "dirichlet_eps",
    "mcts_mode",
    "mcts_top_k_per_head",
    "mcts_max_depth",
    "mcts_root_dirichlet_only",
    "snapshot_opp_deterministic",
    "opponent_stochastic_eps",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "replay_capacity",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "balanced_outcome_sampling",
    "max_policy_staleness_updates",
    "det_eval_gate_win_min",
    "det_eval_gate_turn_limit_max",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
    "hidden_size",
    "num_layers",
    "value_ensemble",
    "lr_scheduler",
    "lr_warmup_steps",
    "lr_total_steps",
    "mcts_eval_cache_size",
    "c_puct_min",
    "c_puct_max",
    "c_puct_schedule",
    "pw_alpha",
    "pw_beta",
    "prior_weight_early",
)

_AZ_BASE: dict[str, int | float | str] = {
    "learning_rate": 0.0003,
    "batch_size": 128,
    "value_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "mcts_simulations": 128,
    "c_puct": 1.1,
    "dirichlet_alpha": 0.3,
    "dirichlet_eps": 0.25,
    "mcts_top_k_per_head": 12,
    "mcts_max_depth": 4,
    "mcts_root_dirichlet_only": 1,
    "snapshot_opp_deterministic": 0,
    "opponent_stochastic_eps": 0.03,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 0.9,
    "temperature_late_value": 0.15,
    "replay_capacity": 200000,
    "num_actors": 8,
    "actor_batch_send": 64,
    "actor_queue_max": 256,
    "sync_every_updates": 2,
    "updates_per_rollout": 2,
    "replay_min_size": 512,
    "balanced_outcome_sampling": 1,
    "max_policy_staleness_updates": 600,
    "det_eval_gate_win_min": 0.45,
    "det_eval_gate_turn_limit_max": 0.65,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
    "hidden_size": 256,
    "num_layers": 2,
    "value_ensemble": 1,
    "lr_scheduler": "none",
    "lr_warmup_steps": 0,
    "lr_total_steps": 0,
    "mcts_eval_cache_size": 10000,
    "c_puct_min": 1.0,
    "c_puct_max": 2.0,
    "c_puct_schedule": "none",
    "pw_alpha": 1.0,
    "pw_beta": 0.5,
    "prior_weight_early": 0.25,
}

DEFAULT_AZ_TREE_HYPERPARAMS: dict[str, int | float | str] = {
    **_AZ_BASE,
    "mcts_mode": "tree",
    "mcts_simulations": 128,
    "mcts_top_k_per_head": 12,
    "mcts_max_depth": 4,
}

DEFAULT_AZ_PROXY_HYPERPARAMS: dict[str, int | float | str] = {
    **_AZ_BASE,
    "mcts_mode": "proxy",
    "mcts_simulations": 32,
    "mcts_top_k_per_head": 8,
    "mcts_max_depth": 1,
}

AZ_TREE_PROFILE_PRESETS: dict[str, dict[str, int | float]] = {
    "fast": {
        "mcts_simulations": 16,
        "mcts_max_depth": 1,
        "mcts_top_k_per_head": 6,
        "mcts_eval_cache_size": 5000,
        "num_actors": 8,
        "actor_batch_send": 16,
        "actor_queue_max": 64,
        "batch_size": 64,
        "replay_capacity": 30000,
        "replay_min_size": 256,
        "updates_per_rollout": 1,
        "sync_every_updates": 1,
        "learning_rate": 0.0003,
    },
    "balanced": {
        "mcts_simulations": 32,
        "mcts_max_depth": 2,
        "mcts_top_k_per_head": 10,
        "mcts_eval_cache_size": 10000,
        "num_actors": 8,
        "actor_batch_send": 32,
        "actor_queue_max": 128,
        "batch_size": 128,
        "replay_capacity": 100000,
        "replay_min_size": 512,
        "updates_per_rollout": 2,
        "sync_every_updates": 2,
        "learning_rate": 0.0003,
    },
    "heavy": {
        "mcts_simulations": 64,
        "mcts_max_depth": 4,
        "mcts_top_k_per_head": 12,
        "mcts_eval_cache_size": 15000,
        "num_actors": 10,
        "actor_batch_send": 64,
        "actor_queue_max": 256,
        "batch_size": 192,
        "replay_capacity": 250000,
        "replay_min_size": 1024,
        "updates_per_rollout": 2,
        "sync_every_updates": 2,
        "learning_rate": 0.0002,
    },
}

AZ_TREE_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "mcts_simulations",
    "mcts_max_depth",
    "mcts_top_k_per_head",
    "num_actors",
    "c_puct",
)

AZ_PROXY_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "num_actors",
    "replay_capacity",
    "updates_per_rollout",
)

AZ_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "training",
        "title": "Обучение",
        "keys": (
            "learning_rate",
            "batch_size",
            "value_loss_weight",
            "l2_weight",
            "lr_scheduler",
            "lr_warmup_steps",
            "lr_total_steps",
        ),
        "default_collapsed": False,
    },
    {
        "id": "mcts",
        "title": "MCTS",
        "keys": (
            "mcts_mode",
            "mcts_simulations",
            "mcts_max_depth",
            "mcts_top_k_per_head",
            "mcts_root_dirichlet_only",
            "mcts_eval_cache_size",
        ),
        "default_collapsed": False,
    },
    {
        "id": "puct",
        "title": "PUCT / exploration",
        "keys": (
            "c_puct",
            "c_puct_min",
            "c_puct_max",
            "c_puct_schedule",
            "dirichlet_alpha",
            "dirichlet_eps",
            "pw_alpha",
            "pw_beta",
            "prior_weight_early",
        ),
        "default_collapsed": True,
    },
    {
        "id": "temperature",
        "title": "Температура",
        "keys": ("temperature_opening_moves", "temperature_opening_value", "temperature_late_value"),
        "default_collapsed": True,
    },
    {
        "id": "actors",
        "title": "Self-play акторы",
        "keys": (
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "updates_per_rollout",
        ),
        "default_collapsed": False,
    },
    {
        "id": "replay_opp",
        "title": "Replay и оппонент",
        "keys": (
            "replay_capacity",
            "replay_min_size",
            "max_policy_staleness_updates",
            "snapshot_opp_deterministic",
            "opponent_stochastic_eps",
            "balanced_outcome_sampling",
        ),
        "default_collapsed": True,
    },
    {
        "id": "outcome_net_eval",
        "title": "Outcome / сеть / DET-eval",
        "keys": (
            "outcome_only",
            "outcome_value_win",
            "outcome_value_loss",
            "outcome_value_draw",
            "hidden_size",
            "num_layers",
            "value_ensemble",
            "det_eval_gate_win_min",
            "det_eval_gate_turn_limit_max",
        ),
        "default_collapsed": True,
    },
)

AZ_FIELD_TOOLTIPS: dict[str, str] = {
    "learning_rate": "Скорость обучения policy-value сети.",
    "batch_size": "Размер батча learner.",
    "value_loss_weight": "Вес value loss.",
    "l2_weight": "L2-регуляризация.",
    "mcts_simulations": "Число MCTS-симуляций (важно для Tree).",
    "c_puct": "Коэффициент PUCT.",
    "dirichlet_alpha": "Alpha шума Дирихле в корне.",
    "dirichlet_eps": "Смешивание с prior (eps).",
    "mcts_mode": "tree или proxy (только чтение).",
    "mcts_top_k_per_head": "Top-K действий на голову.",
    "mcts_max_depth": "Глубина rollout в MCTS (Tree).",
    "mcts_root_dirichlet_only": "1 = шум только в корне.",
    "snapshot_opp_deterministic": "1 = снапшот-оппонент детерминированный.",
    "opponent_stochastic_eps": "Epsilon стохастики оппонента.",
    "temperature_opening_moves": "Ходов с opening temperature.",
    "temperature_opening_value": "Температура в дебюте.",
    "temperature_late_value": "Температура в эндшпиле.",
    "replay_capacity": "Ёмкость replay buffer.",
    "num_actors": "Число акторов self-play.",
    "actor_batch_send": "Размер пачки от актора.",
    "actor_queue_max": "Макс. очередь переходов.",
    "sync_every_updates": "Синхронизация весов каждые N updates.",
    "updates_per_rollout": "Updates learner на rollout.",
    "replay_min_size": "Мин. replay до обучения.",
    "max_policy_staleness_updates": "Макс. устаревание политики.",
    "det_eval_gate_win_min": "Порог win rate для gate.",
    "det_eval_gate_turn_limit_max": "Порог turn limit для gate.",
    "outcome_only": "1 = только outcome reward.",
    "outcome_value_win": "Value при победе.",
    "outcome_value_loss": "Value при поражении.",
    "outcome_value_draw": "Value при ничьей.",
    "hidden_size": "Размер скрытого слоя.",
    "num_layers": "Число слоёв.",
    "value_ensemble": "1 = value ensemble.",
    "lr_scheduler": "Планировщик LR.",
    "lr_warmup_steps": "Шаги warmup LR.",
    "lr_total_steps": "Всего шагов для cosine LR.",
    "mcts_eval_cache_size": "Размер кэша eval в MCTS.",
    "c_puct_min": "Мин. c_puct.",
    "c_puct_max": "Макс. c_puct.",
    "c_puct_schedule": "Расписание c_puct.",
    "pw_alpha": "Progressive widening alpha.",
    "pw_beta": "Progressive widening beta.",
    "prior_weight_early": "Вес prior в opening.",
    "balanced_outcome_sampling": "1 = баланс win/loss в replay.",
}

AZ_PROXY_PROFILE_PRESETS: dict[str, dict[str, int | float]] = {
    "fast": {
        "num_actors": 8,
        "actor_batch_send": 32,
        "actor_queue_max": 128,
        "batch_size": 64,
        "replay_capacity": 50000,
        "replay_min_size": 256,
        "updates_per_rollout": 1,
        "sync_every_updates": 1,
        "learning_rate": 0.0003,
    },
    "balanced": {
        "num_actors": 8,
        "actor_batch_send": 64,
        "actor_queue_max": 256,
        "batch_size": 128,
        "replay_capacity": 200000,
        "replay_min_size": 512,
        "updates_per_rollout": 2,
        "sync_every_updates": 2,
        "learning_rate": 0.0003,
    },
    "heavy": {
        "num_actors": 10,
        "actor_batch_send": 128,
        "actor_queue_max": 512,
        "batch_size": 256,
        "replay_capacity": 500000,
        "replay_min_size": 2048,
        "updates_per_rollout": 3,
        "sync_every_updates": 2,
        "learning_rate": 0.0002,
    },
}
