"""Default Gumbel AlphaZero (gumbel_az) hyperparams for GUI editor."""

from __future__ import annotations

# Поля, не затираемые при смене пресета (LAN/inference — задел под ПК2).
GAZ_INFERENCE_PRESERVE_KEYS: tuple[str, ...] = (
    "inference_server_enabled",
    "inference_server_mode",
    "inference_remote_host",
    "inference_remote_port",
    "inference_remote_auth_token",
    "distributed_actors_enabled",
    "distributed_actors_port",
    "distributed_actors_bind_host",
    "distributed_actors_auth_token",
)

GAZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "value_loss_weight",
    "l2_weight",
    "num_simulations",
    "num_considered_actions",
    "max_depth",
    "value_scale",
    "c_visit",
    "simulate_enemy",
    "joint_action",
    "eval_cache_size",
    "batch_eval_size",
    "replay_capacity",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "balanced_outcome_sampling",
    "max_policy_staleness_updates",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
    "hidden_size",
    "num_layers",
    "value_ensemble",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "lr_scheduler",
    "lr_warmup_steps",
    "lr_total_steps",
    "det_eval_gate_win_min",
    "det_eval_gate_turn_limit_max",
    *GAZ_INFERENCE_PRESERVE_KEYS,
)

_GAZ_BASE: dict[str, int | float | str] = {
    "learning_rate": 0.0003,
    "batch_size": 128,
    "value_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "max_depth": 1,
    "value_scale": 0.1,
    "c_visit": 50.0,
    "simulate_enemy": 0,
    "joint_action": 1,
    "eval_cache_size": 10000,
    "replay_capacity": 100000,
    "num_actors": 8,
    "actor_batch_send": 32,
    "actor_queue_max": 2048,
    "sync_every_updates": 2,
    "updates_per_rollout": 2,
    "replay_min_size": 512,
    "balanced_outcome_sampling": 1,
    "max_policy_staleness_updates": 600,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
    "hidden_size": 256,
    "num_layers": 2,
    "value_ensemble": 1,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 0.9,
    "temperature_late_value": 0.15,
    "lr_scheduler": "none",
    "lr_warmup_steps": 0,
    "lr_total_steps": 0,
    "det_eval_gate_win_min": 0.45,
    "det_eval_gate_turn_limit_max": 0.65,
    # Швы под ПК2 — выключены. Порты GAZ (5565/5567) отличаются от AZ (5555/5557),
    # чтобы AZ и GAZ inference/distributed уживались на одном ПК2.
    "inference_server_enabled": 0,
    "inference_server_mode": "local",
    "inference_remote_host": "127.0.0.1",
    "inference_remote_port": 5565,
    "inference_remote_auth_token": "",
    "distributed_actors_enabled": 0,
    "distributed_actors_port": 5567,
    "distributed_actors_bind_host": "0.0.0.0",
    "distributed_actors_auth_token": "",
}

GAZ_PROFILE_DETECT_ORDER: tuple[str, ...] = ("fast", "balanced", "heavy")

GAZ_PROFILE_PRESETS: dict[str, dict[str, int | float | str]] = {
    "fast": {
        "num_simulations": 16,
        "num_considered_actions": 4,
        "batch_eval_size": 8,
    },
    "balanced": {
        "num_simulations": 32,
        "num_considered_actions": 8,
        "batch_eval_size": 16,
    },
    "heavy": {
        "num_simulations": 64,
        "num_considered_actions": 16,
        "batch_eval_size": 32,
    },
}

# No-preset дефолт = balanced.
DEFAULT_GAZ_HYPERPARAMS: dict[str, int | float | str] = {
    **_GAZ_BASE,
    **GAZ_PROFILE_PRESETS["balanced"],
}

GAZ_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "num_simulations",
    "num_considered_actions",
    "num_actors",
)

GAZ_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "search",
        "title": "Поиск (Gumbel + Sequential Halving)",
        "keys": (
            "num_simulations",
            "num_considered_actions",
            "max_depth",
            "value_scale",
            "c_visit",
            "simulate_enemy",
            "eval_cache_size",
            "batch_eval_size",
            "joint_action",
        ),
        "default_collapsed": False,
    },
    {
        "id": "training",
        "title": "Обучение",
        "keys": (
            "learning_rate",
            "batch_size",
            "value_loss_weight",
            "l2_weight",
            "lr_scheduler",
            "lr_warmup_steps",
            "lr_total_steps",
        ),
        "default_collapsed": False,
    },
    {
        "id": "temperature",
        "title": "Температура",
        "keys": (
            "temperature_opening_moves",
            "temperature_opening_value",
            "temperature_late_value",
        ),
        "default_collapsed": True,
    },
    {
        "id": "actors_replay",
        "title": "Акторы и replay",
        "keys": (
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "updates_per_rollout",
            "replay_capacity",
            "replay_min_size",
            "balanced_outcome_sampling",
            "max_policy_staleness_updates",
        ),
        "default_collapsed": False,
    },
    {
        "id": "arch_outcome",
        "title": "Архитектура и outcome",
        "keys": (
            "hidden_size",
            "num_layers",
            "value_ensemble",
            "outcome_only",
            "outcome_value_win",
            "outcome_value_loss",
            "outcome_value_draw",
            "det_eval_gate_win_min",
            "det_eval_gate_turn_limit_max",
        ),
        "default_collapsed": True,
    },
)

GAZ_FIELD_TOOLTIPS: dict[str, str] = {
    "learning_rate": "Скорость обучения learner.",
    "batch_size": "Размер батча при обновлении весов.",
    "value_loss_weight": "Вес value loss.",
    "l2_weight": "L2-регуляризация.",
    "joint_action": "1 (дефолт) = координатный режим: каждая следующая голова видит уже выбранные действия "
    "предыдущих (движение→стрельба→…), ловит связку «куда встал ↔ кого стреляешь». 0 = головы независимо "
    "(per-head). Стоимость ≈ как при 0. Включён по умолчанию: в A/B joint-сеть в Search/eval разнесла no-joint. "
    "В обучении влияет на self-play; на eval/play действует, если выбран режим инференса Search.",
    "num_simulations": "Бюджет Sequential Halving на голову (на ход).",
    "num_considered_actions": "m: размер Gumbel top-k кандидатов на голову.",
    "max_depth": "Глубина поиска (v1 = 1, root-only).",
    "value_scale": "Масштаб c_scale в sigma(Q) для completed-Q.",
    "c_visit": "Константа c_visit в sigma(Q).",
    "simulate_enemy": "0 (дефолт) = лист оценивает сеть сразу после хода модели — быстро. "
    "1 = симулировать ход врага в depth-1 rollout (точнее, но кратно дороже: тяжёлая эвристика "
    "вызывается на каждого кандидата каждой головы).",
    "eval_cache_size": "Размер LRU-кэша оценок сети.",
    "batch_eval_size": "Сколько листьев батчить в один forward value-сети.",
    "replay_capacity": "Ёмкость replay buffer.",
    "num_actors": "Число параллельных CPU-акторов self-play.",
    "actor_batch_send": "Сколько переходов актор шлёт за раз.",
    "actor_queue_max": "Макс. размер очереди переходов.",
    "sync_every_updates": "Каждые N обновлений learner пишет latest_az_gumbel_az_policy.pth для акторов.",
    "updates_per_rollout": "Градиентных обновлений на один rollout.",
    "replay_min_size": "Мин. размер replay до старта обучения.",
    "balanced_outcome_sampling": "1 = балансировка сэмплинга по исходу.",
    "max_policy_staleness_updates": "Макс. устаревание политики у акторов.",
    "outcome_only": "1 = только outcome reward.",
    "outcome_value_win": "Награда за победу.",
    "outcome_value_loss": "Награда за поражение.",
    "outcome_value_draw": "Награда за ничью.",
    "hidden_size": "Размер скрытого слоя сети.",
    "num_layers": "Число residual-блоков.",
    "value_ensemble": "Число value-голов (ансамбль).",
    "temperature_opening_moves": "Ходов с повышенной температурой (сэмпл из улучшенной π).",
    "temperature_opening_value": "Температура в дебюте.",
    "temperature_late_value": "Температура в эндшпиле.",
    "lr_scheduler": "Тип LR-расписания (none/cosine/...).",
    "lr_warmup_steps": "Шаги warmup для LR.",
    "lr_total_steps": "Всего шагов для LR-расписания.",
    "det_eval_gate_win_min": "Порог win_rate для аннотации gate_pass в DET-eval.",
    "det_eval_gate_turn_limit_max": "Макс. доля turn_limit для gate_pass.",
}
