"""Default Gumbel MuZero hyperparams for GUI editor."""

from __future__ import annotations

GMZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "unroll_steps",
    "value_loss_weight",
    "reward_loss_weight",
    "consistency_loss_weight",
    "l2_weight",
    "max_grad_norm",
    "discount",
    "replay_capacity",
    "actor_device",
    "actor_max_cuda",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "max_policy_staleness_updates",
    "reanalyze_fraction",
    "latent_dim",
    "hidden_dim",
    "action_embed_dim",
    "num_simulations",
    "root_top_k",
    "gumbel_scale",
    "search_temperature",
    "batch_recurrent",
    "tree_reuse",
    "vtrace_full",
    "vtrace_rho_clip",
    "vtrace_c_clip",
    "atom_range",
    "ema_tau",
    "actor_compile",
    "learner_compile",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
)

DEFAULT_GMZ_HYPERPARAMS: dict[str, int | float | str] = {
    "learning_rate": 0.0003,
    "batch_size": 128,
    "unroll_steps": 5,
    "value_loss_weight": 1.0,
    "reward_loss_weight": 1.0,
    "consistency_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "max_grad_norm": 0.5,
    "discount": 0.997,
    "replay_capacity": 250000,
    "actor_device": "cuda",
    "actor_max_cuda": 2,
    "num_actors": 2,
    "actor_batch_send": 64,
    "actor_queue_max": 256,
    "sync_every_updates": 2,
    "updates_per_rollout": 2,
    "replay_min_size": 512,
    "max_policy_staleness_updates": 600,
    "reanalyze_fraction": 0.15,
    "latent_dim": 256,
    "hidden_dim": 256,
    "action_embed_dim": 64,
    "num_simulations": 32,
    "root_top_k": 8,
    "gumbel_scale": 1.0,
    "search_temperature": 0.15,
    "batch_recurrent": 1,
    "tree_reuse": 1,
    "vtrace_full": 1,
    "vtrace_rho_clip": 0.7,
    "vtrace_c_clip": 0.7,
    "atom_range": "tight",
    "ema_tau": 0.005,
    "actor_compile": 1,
    "learner_compile": 1,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 1.0,
    "temperature_late_value": 0.25,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
}

GMZ_PROFILE_PRESETS: dict[str, dict[str, int | float | str]] = {
    "fast": {
        "actor_device": "cuda",
        "actor_max_cuda": 2,
        "num_actors": 2,
        "num_simulations": 16,
        "root_top_k": 4,
        "batch_size": 96,
        "replay_capacity": 120000,
        "reanalyze_fraction": 0.05,
        "consistency_loss_weight": 0.5,
        "vtrace_full": 1,
        "tree_reuse": 1,
        "atom_range": "tight",
        "actor_compile": 1,
        "learner_compile": 1,
    },
    "balanced": {
        "actor_device": "cuda",
        "actor_max_cuda": 2,
        "num_actors": 2,
        "num_simulations": 32,
        "root_top_k": 8,
        "batch_size": 128,
        "replay_capacity": 250000,
        "reanalyze_fraction": 0.15,
        "consistency_loss_weight": 1.0,
        "vtrace_full": 1,
        "tree_reuse": 1,
        "atom_range": "tight",
        "actor_compile": 1,
        "learner_compile": 1,
    },
    "heavy": {
        "actor_device": "cuda",
        "actor_max_cuda": 2,
        "num_actors": 2,
        "num_simulations": 48,
        "root_top_k": 20,
        "batch_size": 160,
        "replay_capacity": 400000,
        "actor_queue_max": 512,
        "reanalyze_fraction": 0.2,
        "consistency_loss_weight": 1.0,
        "vtrace_full": 1,
        "tree_reuse": 1,
        "atom_range": "tight",
        "actor_compile": 0,
        "learner_compile": 0,
    },
}

GMZ_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "num_simulations",
    "root_top_k",
    "unroll_steps",
    "num_actors",
    "vtrace_full",
    "reanalyze_fraction",
)

GMZ_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "training",
        "title": "Обучение",
        "keys": (
            "learning_rate",
            "batch_size",
            "unroll_steps",
            "value_loss_weight",
            "reward_loss_weight",
            "consistency_loss_weight",
            "l2_weight",
            "max_grad_norm",
            "discount",
            "reanalyze_fraction",
        ),
        "default_collapsed": False,
    },
    {
        "id": "search",
        "title": "Поиск (MCTS)",
        "keys": (
            "num_simulations",
            "root_top_k",
            "gumbel_scale",
            "search_temperature",
            "batch_recurrent",
            "tree_reuse",
        ),
        "default_collapsed": False,
    },
    {
        "id": "vtrace",
        "title": "V-trace / IS-коррекция",
        "keys": (
            "vtrace_full",
            "vtrace_rho_clip",
            "vtrace_c_clip",
            "atom_range",
        ),
        "default_collapsed": False,
    },
    {
        "id": "temperature",
        "title": "Температура",
        "keys": (
            "temperature_opening_moves",
            "temperature_opening_value",
            "temperature_late_value",
        ),
        "default_collapsed": True,
    },
    {
        "id": "actors_replay",
        "title": "Акторы и replay",
        "keys": (
            "actor_device",
            "actor_max_cuda",
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "updates_per_rollout",
            "replay_capacity",
            "replay_min_size",
            "max_policy_staleness_updates",
        ),
        "default_collapsed": False,
    },
    {
        "id": "compile_ema",
        "title": "Компиляция и EMA",
        "keys": (
            "actor_compile",
            "learner_compile",
            "ema_tau",
        ),
        "default_collapsed": True,
    },
    {
        "id": "arch_outcome",
        "title": "Архитектура и outcome",
        "keys": (
            "latent_dim",
            "hidden_dim",
            "action_embed_dim",
            "outcome_only",
            "outcome_value_win",
            "outcome_value_loss",
            "outcome_value_draw",
        ),
        "default_collapsed": True,
    },
)

GMZ_FIELD_TOOLTIPS: dict[str, str] = {
    "learning_rate": "Скорость обучения learner.",
    "batch_size": "Размер батча при обновлении весов.",
    "unroll_steps": "Глубина unroll по траектории.",
    "value_loss_weight": "Вес value loss.",
    "reward_loss_weight": "Вес reward loss.",
    "consistency_loss_weight": "Вес SimSiam consistency loss (EMA-цель). 0 = отключить. Рекомендуется 0.5-1.0.",
    "l2_weight": "L2-регуляризация.",
    "max_grad_norm": "Gradient clipping (max norm). 0.5 = рекомендуется для стабильности.",
    "discount": "Дисконт для n-step returns.",
    "reanalyze_fraction": "Доля обучающих шагов, на которых переоцениваются старые траектории (0=выкл, 0.15=15%).",
    "replay_capacity": "Ёмкость replay buffer.",
    "actor_device": "cuda = inference на GPU (по умолчанию, 2 актора). cpu = только CPU. Без CUDA train сам переключит на cpu и 8 акторов (см. лог FALLBACK).",
    "actor_max_cuda": "Макс. GPU-акторов при actor_device=cuda. Ограничение VRAM: 2 актора + learner.",
    "num_actors": "Число параллельных акторов self-play (при cuda фактически min(num_actors, actor_max_cuda)).",
    "actor_batch_send": "Сколько переходов актор шлёт за раз.",
    "actor_queue_max": "Макс. размер очереди переходов.",
    "sync_every_updates": "Синхронизация политики с акторами каждые N updates.",
    "updates_per_rollout": "Градиентных updates на один rollout.",
    "replay_min_size": "Мин. размер replay до старта обучения.",
    "max_policy_staleness_updates": "Макс. устаревание политики у акторов.",
    "latent_dim": "Размерность latent state.",
    "hidden_dim": "Размер скрытого слоя сети.",
    "action_embed_dim": "Размер embedding действия.",
    "num_simulations": "Число MCTS-симуляций на ход.",
    "root_top_k": "Top-K в корне Gumbel-поиска.",
    "gumbel_scale": "Масштаб Gumbel-шума.",
    "search_temperature": "Температура в поиске.",
    "batch_recurrent": "1 = батчевый recurrent inference (быстрее на GPU). 0 = последовательный.",
    "tree_reuse": "1 = переиспользование дерева поиска (warm-start visits/Q) между ходами. Ускоряет сходимость.",
    "vtrace_full": "1 = V-trace на полном unroll (Retrace-стиль). Улучшает качество обучения по старым траекториям.",
    "vtrace_rho_clip": "Ограничение ρ для importance sampling (рекомендуется 0.7-1.0). Меньше = стабильнее.",
    "vtrace_c_clip": "Ограничение c для trace decay в V-trace (рекомендуется 0.7-1.0).",
    "atom_range": "Диапазон атомов: 'tight' = [-1.05,1.05] (рекомендуется), 'legacy' = [-20,20].",
    "ema_tau": "Скорость обновления EMA-цели для consistency loss (Conservative Polyak). 0.005 = медленно.",
    "actor_compile": "1 = torch.compile для актора (10-30% быстрее inference). 0 = выключить.",
    "learner_compile": "1 = torch.compile для learner (15-30% быстрее обучения, нужен CUDA). 0 = выключить.",
    "temperature_opening_moves": "Ходов с повышенной температурой.",
    "temperature_opening_value": "Температура в дебюте.",
    "temperature_late_value": "Температура в эндшпиле.",
    "outcome_only": "1 = только outcome reward.",
    "outcome_value_win": "Награда за победу.",
    "outcome_value_loss": "Награда за поражение.",
    "outcome_value_draw": "Награда за ничью.",
}
