"""Default Gumbel MuZero hyperparams for GUI editor."""

from __future__ import annotations

GMZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "unroll_steps",
    "value_loss_weight",
    "reward_loss_weight",
    "l2_weight",
    "discount",
    "replay_capacity",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "max_policy_staleness_updates",
    "latent_dim",
    "hidden_dim",
    "action_embed_dim",
    "num_simulations",
    "root_top_k",
    "gumbel_scale",
    "search_temperature",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
)

DEFAULT_GMZ_HYPERPARAMS: dict[str, int | float | str] = {
    "learning_rate": 0.0003,
    "batch_size": 128,
    "unroll_steps": 5,
    "value_loss_weight": 1.0,
    "reward_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "discount": 0.997,
    "replay_capacity": 250000,
    "num_actors": 8,
    "actor_batch_send": 64,
    "actor_queue_max": 256,
    "sync_every_updates": 2,
    "updates_per_rollout": 2,
    "replay_min_size": 512,
    "max_policy_staleness_updates": 600,
    "latent_dim": 256,
    "hidden_dim": 256,
    "action_embed_dim": 64,
    "num_simulations": 32,
    "root_top_k": 8,
    "gumbel_scale": 1.0,
    "search_temperature": 0.15,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 1.0,
    "temperature_late_value": 0.25,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
}

GMZ_PROFILE_PRESETS: dict[str, dict[str, int | float]] = {
    "fast": {
        "num_actors": 8,
        "num_simulations": 16,
        "root_top_k": 4,
        "batch_size": 96,
        "replay_capacity": 120000,
    },
    "balanced": {
        "num_actors": 8,
        "num_simulations": 32,
        "root_top_k": 8,
        "batch_size": 128,
        "replay_capacity": 250000,
    },
    "heavy": {
        "num_actors": 8,
        "num_simulations": 128,
        "root_top_k": 20,
        "batch_size": 160,
        "replay_capacity": 400000,
        "actor_queue_max": 512,
    },
}

GMZ_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "num_simulations",
    "root_top_k",
    "unroll_steps",
    "num_actors",
)

GMZ_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "training",
        "title": "Обучение",
        "keys": (
            "learning_rate",
            "batch_size",
            "unroll_steps",
            "value_loss_weight",
            "reward_loss_weight",
            "l2_weight",
            "discount",
        ),
        "default_collapsed": False,
    },
    {
        "id": "search",
        "title": "Поиск (MCTS)",
        "keys": ("num_simulations", "root_top_k", "gumbel_scale", "search_temperature"),
        "default_collapsed": False,
    },
    {
        "id": "temperature",
        "title": "Температура",
        "keys": (
            "temperature_opening_moves",
            "temperature_opening_value",
            "temperature_late_value",
        ),
        "default_collapsed": True,
    },
    {
        "id": "actors_replay",
        "title": "Акторы и replay",
        "keys": (
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "updates_per_rollout",
            "replay_capacity",
            "replay_min_size",
            "max_policy_staleness_updates",
        ),
        "default_collapsed": False,
    },
    {
        "id": "arch_outcome",
        "title": "Архитектура и outcome",
        "keys": (
            "latent_dim",
            "hidden_dim",
            "action_embed_dim",
            "outcome_only",
            "outcome_value_win",
            "outcome_value_loss",
            "outcome_value_draw",
        ),
        "default_collapsed": True,
    },
)

GMZ_FIELD_TOOLTIPS: dict[str, str] = {
    "learning_rate": "Скорость обучения learner.",
    "batch_size": "Размер батча при обновлении весов.",
    "unroll_steps": "Глубина unroll по траектории.",
    "value_loss_weight": "Вес value loss.",
    "reward_loss_weight": "Вес reward loss.",
    "l2_weight": "L2-регуляризация.",
    "discount": "Дисконт для n-step returns.",
    "replay_capacity": "Ёмкость replay buffer.",
    "num_actors": "Число параллельных акторов self-play.",
    "actor_batch_send": "Сколько переходов актор шлёт за раз.",
    "actor_queue_max": "Макс. размер очереди переходов.",
    "sync_every_updates": "Синхронизация политики с акторами каждые N updates.",
    "updates_per_rollout": "Градиентных updates на один rollout.",
    "replay_min_size": "Мин. размер replay до старта обучения.",
    "max_policy_staleness_updates": "Макс. устаревание политики у акторов.",
    "latent_dim": "Размерность latent state.",
    "hidden_dim": "Размер скрытого слоя сети.",
    "action_embed_dim": "Размер embedding действия.",
    "num_simulations": "Число MCTS-симуляций на ход.",
    "root_top_k": "Top-K в корне Gumbel-поиска.",
    "gumbel_scale": "Масштаб Gumbel-шума.",
    "search_temperature": "Температура в поиске.",
    "temperature_opening_moves": "Ходов с повышенной температурой.",
    "temperature_opening_value": "Температура в дебюте.",
    "temperature_late_value": "Температура в эндшпиле.",
    "outcome_only": "1 = только outcome reward.",
    "outcome_value_win": "Награда за победу.",
    "outcome_value_loss": "Награда за поражение.",
    "outcome_value_draw": "Награда за ничью.",
}
