"""Default PHOENIX hyperparams for GUI editor."""

from __future__ import annotations

PHOENIX_HYPERPARAM_KEYS: tuple[str, ...] = (
    "replay_ratio",
    "reset_interval",
    "anneal_steps",
    "shrink_alpha",
    "nstep_start",
    "nstep_end",
    "gamma_start",
    "gamma_end",
    "target_ema_rl",
    "target_ema_spr",
    "replay_capacity",
    "spr_horizon_K",
    "spr_coef",
    "ve_horizon",
    "ve_steve",
    "dynamics_type",
    "emb_dim",
    "noisy",
    "dueling",
    "hidden_size",
    "num_layers",
    "n_ensemble",
    "iqn_num_quantiles",
    "iqn_num_target_quantiles",
    "iqn_num_tau_samples",
    "iqn_embed_dim",
)

DEFAULT_PHOENIX_HYPERPARAMS: dict[str, int | float | str] = {
    "replay_ratio": 2,
    "reset_interval": 40000,
    "anneal_steps": 10000,
    "shrink_alpha": 0.5,
    "nstep_start": 10,
    "nstep_end": 3,
    "gamma_start": 0.97,
    "gamma_end": 0.99,
    "target_ema_rl": 0.005,
    "target_ema_spr": 0.01,
    "replay_capacity": 200000,
    "spr_horizon_K": 5,
    "spr_coef": 2.0,
    "ve_horizon": 3,
    "ve_steve": 0,
    "dynamics_type": "mlp",
    "emb_dim": 64,
    "noisy": 0,
    "dueling": 0,
    "hidden_size": 256,
    "num_layers": 2,
    "n_ensemble": 1,
    "iqn_num_quantiles": 32,
    "iqn_num_target_quantiles": 32,
    "iqn_num_tau_samples": 32,
    "iqn_embed_dim": 64,
}

PHOENIX_BASIC_KEYS: tuple[str, ...] = (
    "replay_ratio",
    "reset_interval",
    "spr_horizon_K",
    "ve_horizon",
    "nstep_start",
    "nstep_end",
    "gamma_start",
    "hidden_size",
)

PHOENIX_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "bbf",
        "title": "BBF / расписания",
        "keys": (
            "replay_ratio",
            "reset_interval",
            "anneal_steps",
            "shrink_alpha",
            "nstep_start",
            "nstep_end",
            "gamma_start",
            "gamma_end",
            "replay_capacity",
        ),
        "default_collapsed": False,
    },
    {
        "id": "spr_ve",
        "title": "SPR и value-expansion",
        "keys": (
            "spr_horizon_K",
            "spr_coef",
            "ve_horizon",
            "ve_steve",
        ),
        "default_collapsed": False,
    },
    {
        "id": "ema",
        "title": "Target EMA",
        "keys": (
            "target_ema_rl",
            "target_ema_spr",
        ),
        "default_collapsed": True,
    },
    {
        "id": "arch",
        "title": "Архитектура сети",
        "keys": (
            "hidden_size",
            "num_layers",
            "n_ensemble",
            "emb_dim",
            "dynamics_type",
            "dueling",
            "noisy",
        ),
        "default_collapsed": False,
    },
    {
        "id": "iqn",
        "title": "IQN",
        "keys": (
            "iqn_num_quantiles",
            "iqn_num_target_quantiles",
            "iqn_num_tau_samples",
            "iqn_embed_dim",
        ),
        "default_collapsed": True,
    },
)

PHOENIX_FIELD_TOOLTIPS: dict[str, str] = {
    "replay_ratio": "Сколько градиентных шагов на один env-шаг (BBF replay ratio).",
    "reset_interval": "Период reset+shrink весов (градиентные шаги).",
    "anneal_steps": "Длина аннелинга n-step и γ.",
    "shrink_alpha": "Доля старых весов после reset (shrink-and-perturb).",
    "nstep_start": "Стартовый n-step для TD-таргетов.",
    "nstep_end": "Финальный n-step после аннелинга.",
    "gamma_start": "Стартовый γ.",
    "gamma_end": "Финальный γ после аннелинга.",
    "target_ema_rl": "EMA-коэффициент target-сети для RL (IQN).",
    "target_ema_spr": "EMA-коэффициент encoder/projection для SPR.",
    "replay_capacity": "Ёмкость sequence-replay (окна длиной max(K, ve_horizon)+1).",
    "spr_horizon_K": "Горизонт SPR consistency (BYOL на латенте).",
    "spr_coef": "Вес SPR-loss относительно IQN TD.",
    "ve_horizon": "Горизонт латентного value-expansion (0 = обычный 1-step IQN).",
    "ve_steve": "STEVE-усреднение таргетов по горизонтам (1) или фикс. y_ve_horizon (0).",
    "dynamics_type": "Тип латентной динамики: mlp или gru.",
    "emb_dim": "Размерность action-embed (сумма по головам).",
    "noisy": "NoisyNet в IQN (0 — дефолт PHOENIX, exploration через ε-greedy).",
    "dueling": "Dueling-архитектура IQN-голов (как опция DQN).",
    "hidden_size": "Размер скрытого слоя encoder/dynamics.",
    "num_layers": "Число ResidualBlock в encoder.",
    "n_ensemble": "Размер ансамбля IQN-голов (1 = без ансамбля).",
    "iqn_num_quantiles": "Число квантилей online-IQN.",
    "iqn_num_target_quantiles": "Число квантилей target-IQN.",
    "iqn_num_tau_samples": "Сэмплы τ на шаг обучения.",
    "iqn_embed_dim": "Размерность IQN embedding.",
}
