"""Default PHOENIX hyperparams for GUI editor."""

from __future__ import annotations

PHOENIX_HYPERPARAM_KEYS: tuple[str, ...] = (
    "replay_ratio",
    "reset_interval",
    "anneal_steps",
    "shrink_alpha",
    "nstep_start",
    "nstep_end",
    "gamma_start",
    "gamma_end",
    "target_ema_rl",
    "target_ema_spr",
    "replay_capacity",
    "batch_size",
    "replay_min_size",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "actor_epsilon_mode",
    "actor_eps_floor_min",
    "actor_eps_floor_max",
    "distributed_actors_enabled",
    "distributed_rollout_port",
    "distributed_bind_host",
    "distributed_auth_token",
    "distributed_local_episode_fraction",
    "distributed_pc2_num_workers",
    "distributed_actors_drain_sec",
    "distributed_wait_pc2",
    "distributed_wait_pc2_timeout_sec",
    "distributed_bind_retry_sec",
    "dist_zmq_hwm",
    "dist_max_windows_per_msg",
    "spr_horizon_K",
    "spr_coef",
    "ve_horizon",
    "ve_steve",
    "ve_latent_bootstrap",
    "iqn_kappa",
    "dynamics_type",
    "emb_dim",
    "noisy",
    "dueling",
    "hidden_size",
    "num_layers",
    "n_ensemble",
    "iqn_num_quantiles",
    "iqn_num_target_quantiles",
    "iqn_num_tau_samples",
    "iqn_embed_dim",
)

DEFAULT_PHOENIX_HYPERPARAMS: dict[str, int | float | str] = {
    "replay_ratio": 2,
    "reset_interval": 40000,
    "anneal_steps": 10000,
    "shrink_alpha": 0.5,
    "nstep_start": 10,
    "nstep_end": 3,
    "gamma_start": 0.97,
    "gamma_end": 0.99,
    "target_ema_rl": 0.005,
    "target_ema_spr": 0.01,
    "replay_capacity": 200000,
    "batch_size": 32,
    "replay_min_size": 256,
    "num_actors": 1,
    "actor_batch_send": 32,
    "actor_queue_max": 256,
    "sync_every_updates": 200,
    "actor_epsilon_mode": "apex",
    "actor_eps_floor_min": 0.02,
    "actor_eps_floor_max": 0.20,
    "distributed_actors_enabled": 0,
    "distributed_rollout_port": 5562,
    "distributed_bind_host": "0.0.0.0",
    "distributed_auth_token": "",
    "distributed_local_episode_fraction": 0.7,
    "distributed_pc2_num_workers": 8,
    "distributed_actors_drain_sec": 30.0,
    "distributed_wait_pc2": 0,
    "distributed_wait_pc2_timeout_sec": 600.0,
    "distributed_bind_retry_sec": 25.0,
    "dist_zmq_hwm": 256,
    "dist_max_windows_per_msg": 64,
    "spr_horizon_K": 5,
    "spr_coef": 2.0,
    "ve_horizon": 3,
    "ve_steve": 0,
    "ve_latent_bootstrap": 0,
    "iqn_kappa": 1.0,
    "dynamics_type": "mlp",
    "emb_dim": 64,
    "noisy": 0,
    "dueling": 0,
    "hidden_size": 256,
    "num_layers": 2,
    "n_ensemble": 1,
    "iqn_num_quantiles": 32,
    "iqn_num_target_quantiles": 32,
    "iqn_num_tau_samples": 32,
    "iqn_embed_dim": 64,
}

PHOENIX_BASIC_KEYS: tuple[str, ...] = (
    "replay_ratio",
    "batch_size",
    "reset_interval",
    "spr_horizon_K",
    "ve_horizon",
    "num_actors",
    "nstep_start",
    "nstep_end",
    "gamma_start",
    "hidden_size",
)

PHOENIX_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "bbf",
        "title": "BBF / расписания",
        "keys": (
            "replay_ratio",
            "reset_interval",
            "anneal_steps",
            "shrink_alpha",
            "nstep_start",
            "nstep_end",
            "gamma_start",
            "gamma_end",
            "replay_capacity",
            "batch_size",
            "replay_min_size",
        ),
        "default_collapsed": False,
    },
    {
        "id": "actors",
        "title": "Акторы / distributed",
        "keys": (
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "actor_epsilon_mode",
            "actor_eps_floor_min",
            "actor_eps_floor_max",
            "distributed_actors_enabled",
            "distributed_rollout_port",
            "distributed_bind_host",
            "distributed_auth_token",
            "distributed_local_episode_fraction",
            "distributed_pc2_num_workers",
            "distributed_actors_drain_sec",
            "distributed_wait_pc2",
            "distributed_wait_pc2_timeout_sec",
            "distributed_bind_retry_sec",
            "dist_zmq_hwm",
            "dist_max_windows_per_msg",
        ),
        "default_collapsed": False,
    },
    {
        "id": "spr_ve",
        "title": "SPR и value-expansion",
        "keys": (
            "spr_horizon_K",
            "spr_coef",
            "ve_horizon",
            "ve_steve",
            "ve_latent_bootstrap",
            "iqn_kappa",
        ),
        "default_collapsed": False,
    },
    {
        "id": "ema",
        "title": "Target EMA",
        "keys": (
            "target_ema_rl",
            "target_ema_spr",
        ),
        "default_collapsed": True,
    },
    {
        "id": "arch",
        "title": "Архитектура сети",
        "keys": (
            "hidden_size",
            "num_layers",
            "n_ensemble",
            "emb_dim",
            "dynamics_type",
            "dueling",
            "noisy",
        ),
        "default_collapsed": False,
    },
    {
        "id": "iqn",
        "title": "IQN",
        "keys": (
            "iqn_num_quantiles",
            "iqn_num_target_quantiles",
            "iqn_num_tau_samples",
            "iqn_embed_dim",
        ),
        "default_collapsed": True,
    },
)

PHOENIX_FIELD_TOOLTIPS: dict[str, str] = {
    "replay_ratio": "Сколько градиентных шагов на один env-шаг (BBF replay ratio).",
    "reset_interval": "Период reset+shrink весов (градиентные шаги).",
    "anneal_steps": "Длина аннелинга n-step и γ.",
    "shrink_alpha": "Доля старых весов после reset (shrink-and-perturb).",
    "nstep_start": "Стартовый n-step для TD-таргетов.",
    "nstep_end": "Финальный n-step после аннелинга.",
    "gamma_start": "Стартовый γ.",
    "gamma_end": "Финальный γ после аннелинга.",
    "target_ema_rl": "EMA-коэффициент target-сети для RL (IQN).",
    "target_ema_spr": "EMA-коэффициент encoder/projection для SPR.",
    "replay_capacity": "Ёмкость sequence-replay (окна длиной max(K, ve_horizon)+1).",
    "batch_size": "Размер батча окон при learn_step.",
    "replay_min_size": "Минимум окон в replay перед обучением.",
    "num_actors": "Число CPU-акторов PHOENIX на ПК1. 1 = старый single-process путь.",
    "actor_batch_send": "Сколько sequence windows актор отправляет одним батчем learner'у.",
    "actor_queue_max": "Максимальный размер очереди actor→learner.",
    "sync_every_updates": "Как часто learner публикует свежие веса для акторов.",
    "actor_epsilon_mode": "Режим exploration акторов: apex или global.",
    "actor_eps_floor_min": "Минимальный ε-floor для самого жадного актора.",
    "actor_eps_floor_max": "Максимальный ε-floor для самого исследующего актора.",
    "distributed_actors_enabled": "1 = принимать PHOENIX sequence windows с ПК2.",
    "distributed_rollout_port": "Порт приёма PHOENIX данных с ПК2 (по умолчанию 5562).",
    "distributed_bind_host": "Адрес bind на ПК1 для PHOENIX receiver.",
    "distributed_auth_token": "Общий пароль ПК1↔ПК2 для PHOENIX distributed.",
    "distributed_local_episode_fraction": "Доля эпизодов на ПК1; остальное — ПК2.",
    "distributed_pc2_num_workers": "Число PHOENIX env-воркеров на ПК2.",
    "distributed_actors_drain_sec": "Максимум секунд drain после лимита эпизодов.",
    "distributed_wait_pc2": "Ждать hello от ПК2 перед стартом сбора.",
    "distributed_wait_pc2_timeout_sec": "Сколько ждать ПК2; 0 = бесконечно.",
    "distributed_bind_retry_sec": "Сколько секунд повторять bind порта, если он занят.",
    "dist_zmq_hwm": "ZMQ high-water mark для PHOENIX PC2 транспортного канала.",
    "dist_max_windows_per_msg": "Максимум sequence windows в одном remote-сообщении.",
    "spr_horizon_K": "Горизонт SPR consistency (BYOL на латенте).",
    "spr_coef": "Вес SPR-loss относительно IQN TD.",
    "ve_horizon": "Горизонт латентного value-expansion (0 = обычный 1-step IQN).",
    "ve_steve": "STEVE-усреднение таргетов по горизонтам (1) или фикс. y_ve_horizon (0).",
    "ve_latent_bootstrap": "1 = bootstrap value-expansion из предсказанного латента.",
    "iqn_kappa": "Huber kappa для IQN quantile loss.",
    "dynamics_type": "Тип латентной динамики: mlp или gru.",
    "emb_dim": "Размерность action-embed (сумма по головам).",
    "noisy": "NoisyNet в IQN (0 — дефолт PHOENIX, exploration через ε-greedy).",
    "dueling": "Dueling-архитектура IQN-голов (как опция DQN).",
    "hidden_size": "Размер скрытого слоя encoder/dynamics.",
    "num_layers": "Число ResidualBlock в encoder.",
    "n_ensemble": "Размер ансамбля IQN-голов (1 = без ансамбля).",
    "iqn_num_quantiles": "Число квантилей online-IQN.",
    "iqn_num_target_quantiles": "Число квантилей target-IQN.",
    "iqn_num_tau_samples": "Сэмплы τ на шаг обучения.",
    "iqn_embed_dim": "Размерность IQN embedding.",
}

PHOENIX_DIST_ACTORS_GUI_TOOLTIP = (
    "Распределённые акторы PHOENIX: второй ПК (ПК2) помогает собирать sequence windows для общего replay на ПК1.\n\n"
    "ПК2 только играет и шлёт окна H+1; обучение и GPU остаются на ПК1.\n"
    "Порядок: 1) включить Distributed actors и стартовать train на ПК1; "
    "2) запустить tools\\pc2_phoenix_actors.bat на ПК2.\n\n"
    "По умолчанию выключено. При num_actors=1 и выключенном ПК2 PHOENIX остаётся в старом single-process режиме."
)

PHOENIX_DIST_WAIT_PC2_GUI_TOOLTIP = (
    "Train поднимает PHOENIX receiver на порту 5562 и пишет phoenix_dist_train_context.json на SMB, "
    "но локальные акторы не стартуют, пока с ПК2 не придёт hello от всех воркеров.\n\n"
    "Таймаут 0 = ждать бесконечно."
)
