"""Default Sampled MuZero hyperparams for GUI editor."""

from __future__ import annotations

SMZ_HYPERPARAM_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "unroll_steps",
    "value_loss_weight",
    "reward_loss_weight",
    "consistency_loss_weight",
    "l2_weight",
    "max_grad_norm",
    "discount",
    "replay_capacity",
    "num_actors",
    "actor_batch_send",
    "actor_queue_max",
    "sync_every_updates",
    "updates_per_rollout",
    "replay_min_size",
    "max_policy_staleness_updates",
    "reanalyze_fraction",
    "latent_dim",
    "hidden_dim",
    "num_layers",
    "action_embed_dim",
    "num_samples",
    "sample_temperature",
    "search_temperature",
    "prior_weight",
    "dedup",
    "tbptt_truncate",
    "vtrace_full",
    "vtrace_rho_clip",
    "vtrace_c_clip",
    "atom_range",
    "ema_tau",
    "learner_compile",
    "actor_device",
    "actor_max_cuda",
    "num_env_workers",
    "inference_server_enabled",
    "inference_server_mode",
    "inference_server_compile",
    "inference_batch_size",
    "inference_batch_interval_ms",
    "inference_request_queue_max",
    "inference_timeout",
    "clear_tree_on_weight_sync",
    "temperature_opening_moves",
    "temperature_opening_value",
    "temperature_late_value",
    "outcome_only",
    "outcome_value_win",
    "outcome_value_loss",
    "outcome_value_draw",
)

DEFAULT_SMZ_HYPERPARAMS: dict[str, int | float | str] = {
    "learning_rate": 0.0003,
    "batch_size": 160,
    "unroll_steps": 5,
    "value_loss_weight": 1.0,
    "reward_loss_weight": 1.0,
    "consistency_loss_weight": 1.0,
    "l2_weight": 1e-6,
    "max_grad_norm": 0.5,
    "discount": 0.997,
    "replay_capacity": 400000,
    "num_actors": 8,
    "actor_batch_send": 64,
    "actor_queue_max": 256,
    "sync_every_updates": 20,
    "updates_per_rollout": 3,
    "replay_min_size": 512,
    "max_policy_staleness_updates": 600,
    "reanalyze_fraction": 0.15,
    "latent_dim": 256,
    "hidden_dim": 256,
    "num_layers": 2,
    "action_embed_dim": 64,
    "num_samples": 24,
    "sample_temperature": 1.0,
    "search_temperature": 0.15,
    "prior_weight": 0.0,
    "dedup": 1,
    "tbptt_truncate": 3,
    "vtrace_full": 1,
    "vtrace_rho_clip": 0.7,
    "vtrace_c_clip": 0.7,
    "atom_range": "tight",
    "ema_tau": 0.005,
    "learner_compile": 1,
    "actor_device": "cuda",
    "actor_max_cuda": 2,
    "num_env_workers": 6,
    "inference_server_enabled": 0,
    "inference_server_mode": "local",
    "inference_server_compile": 1,
    "inference_batch_size": 8,
    "inference_batch_interval_ms": 20.0,
    "inference_request_queue_max": 32,
    "inference_timeout": 5.0,
    "clear_tree_on_weight_sync": 0,
    "temperature_opening_moves": 12,
    "temperature_opening_value": 1.0,
    "temperature_late_value": 0.25,
    "outcome_only": 1,
    "outcome_value_win": 1.0,
    "outcome_value_loss": -1.0,
    "outcome_value_draw": -0.25,
}

SMZ_PROFILE_DETECT_ORDER: tuple[str, ...] = ("fast", "balanced", "heavy")

SMZ_PROFILE_PRESETS: dict[str, dict[str, int | float | str]] = {
    "fast": {
        "num_samples": 16,
        "batch_size": 128,
        "replay_capacity": 200000,
        "num_actors": 4,
        "reanalyze_fraction": 0.05,
        "consistency_loss_weight": 0.5,
        "vtrace_full": 1,
        "atom_range": "tight",
        "learner_compile": 1,
    },
    "balanced": {
        "num_samples": 24,
        "batch_size": 160,
        "replay_capacity": 400000,
        "num_actors": 8,
        "reanalyze_fraction": 0.15,
        "consistency_loss_weight": 1.0,
        "vtrace_full": 1,
        "atom_range": "tight",
        "learner_compile": 1,
    },
    "heavy": {
        "num_samples": 32,
        "batch_size": 256,
        "replay_capacity": 600000,
        "num_actors": 12,
        "reanalyze_fraction": 0.15,
        "consistency_loss_weight": 1.0,
        "vtrace_full": 1,
        "atom_range": "tight",
        "learner_compile": 1,
    },
}

# No-preset дефолт = balanced.
DEFAULT_SMZ_HYPERPARAMS = {**DEFAULT_SMZ_HYPERPARAMS, **SMZ_PROFILE_PRESETS["balanced"]}

SMZ_BASIC_KEYS: tuple[str, ...] = (
    "learning_rate",
    "batch_size",
    "num_samples",
    "search_temperature",
    "unroll_steps",
    "num_actors",
    "vtrace_full",
    "reanalyze_fraction",
)

SMZ_GROUPS: tuple[dict[str, object], ...] = (
    {
        "id": "training",
        "title": "Обучение",
        "keys": (
            "learning_rate",
            "batch_size",
            "unroll_steps",
            "value_loss_weight",
            "reward_loss_weight",
            "consistency_loss_weight",
            "l2_weight",
            "max_grad_norm",
            "discount",
            "reanalyze_fraction",
        ),
        "default_collapsed": False,
    },
    {
        "id": "search",
        "title": "Поиск (Sampled)",
        "keys": (
            "num_samples",
            "sample_temperature",
            "search_temperature",
            "prior_weight",
            "dedup",
            "tbptt_truncate",
        ),
        "default_collapsed": False,
    },
    {
        "id": "vtrace",
        "title": "V-trace / IS-коррекция",
        "keys": (
            "vtrace_full",
            "vtrace_rho_clip",
            "vtrace_c_clip",
            "atom_range",
        ),
        "default_collapsed": False,
    },
    {
        "id": "temperature",
        "title": "Температура",
        "keys": (
            "temperature_opening_moves",
            "temperature_opening_value",
            "temperature_late_value",
        ),
        "default_collapsed": True,
    },
    {
        "id": "actors_replay",
        "title": "Акторы и replay",
        "keys": (
            "num_actors",
            "actor_batch_send",
            "actor_queue_max",
            "sync_every_updates",
            "updates_per_rollout",
            "replay_capacity",
            "replay_min_size",
            "max_policy_staleness_updates",
        ),
        "default_collapsed": False,
    },
    {
        "id": "compile_ema",
        "title": "Компиляция и EMA",
        "keys": (
            "learner_compile",
            "ema_tau",
        ),
        "default_collapsed": True,
    },
    {
        "id": "inference_server",
        "title": "Inference Server",
        "keys": (
            "inference_server_enabled",
            "inference_server_mode",
            "num_env_workers",
            "inference_batch_size",
            "inference_batch_interval_ms",
            "inference_request_queue_max",
            "inference_timeout",
            "inference_server_compile",
            "clear_tree_on_weight_sync",
            "actor_max_cuda",
        ),
        "default_collapsed": True,
    },
    {
        "id": "arch_outcome",
        "title": "Архитектура и outcome",
        "keys": (
            "latent_dim",
            "hidden_dim",
            "num_layers",
            "action_embed_dim",
            "actor_device",
            "outcome_only",
            "outcome_value_win",
            "outcome_value_loss",
            "outcome_value_draw",
        ),
        "default_collapsed": True,
    },
)

SMZ_FIELD_TOOLTIPS: dict[str, str] = {
    "learning_rate": "Скорость обучения learner.",
    "batch_size": "Размер батча при обновлении весов.",
    "unroll_steps": "Глубина unroll по траектории.",
    "value_loss_weight": "Вес value loss.",
    "reward_loss_weight": "Вес reward loss.",
    "consistency_loss_weight": "Вес SimSiam consistency loss (EMA-цель). 0 = отключить.",
    "l2_weight": "L2-регуляризация.",
    "max_grad_norm": "Gradient clipping (max norm).",
    "discount": "Дисконт для n-step returns.",
    "reanalyze_fraction": "Доля шагов с переоценкой старых траекторий (0=выкл, 0.15=15%).",
    "replay_capacity": "Ёмкость replay buffer.",
    "num_actors": "Число параллельных акторов self-play.",
    "actor_batch_send": "Сколько переходов актор шлёт за раз.",
    "actor_queue_max": "Макс. размер очереди переходов.",
    "sync_every_updates": "Каждые N gradient updates learner сохраняет веса для акторов.",
    "updates_per_rollout": "Градиентных updates на один rollout.",
    "replay_min_size": "Мин. размер replay до старта обучения.",
    "max_policy_staleness_updates": "Макс. устаревание политики у акторов.",
    "latent_dim": "Размерность latent state.",
    "hidden_dim": "Размер скрытого слоя сети.",
    "num_layers": "Число слоёв в сети.",
    "action_embed_dim": "Размер embedding действия.",
    "num_samples": "K — число joint-ходов, сэмплируемых из приора на каждый шаг поиска.",
    "sample_temperature": "Температура сэмплирования joint-ходов из приора (1.0 = стандартная).",
    "search_temperature": "Температура в финальном поиске.",
    "prior_weight": "Доля приора сети в корневой политике. 0 = только IS-цель.",
    "dedup": "1 = дедупликация joint-сэмплов (убирает точные копии ходов).",
    "tbptt_truncate": "Длина сегмента TBPTT (Truncated BPTT) при unroll.",
    "vtrace_full": "1 = V-trace на полном unroll (Retrace-стиль).",
    "vtrace_rho_clip": "Ограничение ρ для importance sampling (рекомендуется 0.7-1.0).",
    "vtrace_c_clip": "Ограничение c для trace decay в V-trace (рекомендуется 0.7-1.0).",
    "atom_range": "Диапазон атомов: 'tight' = [-1.05,1.05], 'legacy' = [-20,20].",
    "ema_tau": "Скорость обновления EMA-цели для consistency loss.",
    "learner_compile": "1 = torch.compile для learner на CUDA.",
    "actor_device": "cuda / cpu — устройство для акторов self-play.",
    "actor_max_cuda": "Макс. число CUDA-акторов (variant A).",
    "num_env_workers": "Число CPU env-воркеров (variant B).",
    "inference_server_enabled": (
        "Вкл inference-server (variant B): отдельный GPU-сервер крутит поиск, "
        "env-воркеры на CPU. По умолчанию выкл."
    ),
    "inference_server_mode": (
        "local — сервер на этой машине; remote — сервер на ПК2 "
        "(настройки host/port в remote_is_smz.json)."
    ),
    "inference_server_compile": (
        "torch.compile сервера (на Windows без triton мягко пропускается)."
    ),
    "inference_batch_size": "Макс. размер батча запросов на сервере.",
    "inference_batch_interval_ms": "Окно сбора батча, мс.",
    "inference_request_queue_max": "Глубина очереди запросов к серверу.",
    "inference_timeout": "Таймаут ответа сервера, сек.",
    "clear_tree_on_weight_sync": (
        "Сброс tree-reuse при синке весов (для sampled v1 неактуально, оставьте 0)."
    ),
    "temperature_opening_moves": "Ходов с повышенной температурой.",
    "temperature_opening_value": "Температура в дебюте.",
    "temperature_late_value": "Температура в эндшпиле.",
    "outcome_only": "1 = только outcome reward.",
    "outcome_value_win": "Награда за победу.",
    "outcome_value_loss": "Награда за поражение.",
    "outcome_value_draw": "Награда за ничью.",
}
