"""Слой иерархических фаз W40k: окна решений и опции действий.

Аддитивный слой над Warhammer40kEnv. Не меняет поведение движка — только
описывает ход как последовательность DecisionWindow со списком ActionOption
и компилирует их обратно в плоский action_dict.
"""

from core.engine.phases import phase_engine, stratagem_engine
from core.engine.phases.legacy_compiler import (
    compile_options_to_action_dict,
    default_action_dict,
)
from core.engine.phases.obs_features import (
    PHASE_OBS_EXTENSION_SIZE,
    append_phase_obs_features,
    base_observation_length,
    build_phase_obs_signature_suffix,
    describe_obs_dim_mismatch,
    legacy_observation_space_size,
    phase_obs_features_enabled,
    phase_obs_vector,
    resolve_phase_obs_features,
)
from core.engine.phases.option_generator import (
    charge_options_for_unit,
    command_window,
    fight_stratagem_options_for_unit,
    generate_windows,
    movement_options_for_unit,
    shooting_options_for_unit,
)
from core.engine.phases.reaction_windows import (
    build_reaction_windows,
    windowed_reaction_windows_enabled,
)
from core.engine.phases.replay_meta import (
    ReplayPhaseMeta,
    az_transition_from_rollout_dict,
    az_transition_to_rollout_dict,
    capture_replay_phase_meta,
    gmz_transition_from_rollout_dict,
    gmz_transition_to_rollout_dict,
    replay_phase_meta_enabled,
    snapshot_cp_before,
    wire_dict_for_phase_meta,
)
from core.engine.phases.stratagem_engine import apply as apply_stratagem
from core.engine.phases.stratagems import (
    REGISTRY,
    StratagemDef,
    Trigger,
    UsageLimit,
    by_id,
    for_phase,
    for_trigger,
    legal_stratagem_options,
)
from core.engine.phases.types import (
    ActionKind,
    ActionOption,
    DecisionWindow,
    Phase,
    PhaseResult,
    PhaseState,
    PhaseTurnState,
    SubStep,
    Timing,
)
from core.engine.phases.windowed_selfplay import (
    command_replay_meta_from_action,
    make_charge_decide_from_action_dict,
    make_command_decide_from_action_dict,
    make_fight_decide_from_action_dict,
    make_movement_decide_from_action_dict,
    make_shooting_decide_from_action_dict,
    merge_command_meta_into,
    merge_windowed_meta_into,
    run_model_charge_from_action,
    run_model_command_from_action,
    run_model_fight_from_action,
    run_model_movement_from_action,
    run_model_shooting_from_action,
    run_model_turn_from_action,
    turn_replay_meta_from_action,
    windowed_selfplay_enabled,
)

__all__ = [
    "phase_obs_features_enabled",
    "PHASE_OBS_EXTENSION_SIZE",
    "base_observation_length",
    "legacy_observation_space_size",
    "build_phase_obs_signature_suffix",
    "append_phase_obs_features",
    "phase_obs_vector",
    "resolve_phase_obs_features",
    "describe_obs_dim_mismatch",
    "ReplayPhaseMeta",
    "replay_phase_meta_enabled",
    "capture_replay_phase_meta",
    "snapshot_cp_before",
    "az_transition_to_rollout_dict",
    "az_transition_from_rollout_dict",
    "gmz_transition_to_rollout_dict",
    "gmz_transition_from_rollout_dict",
    "wire_dict_for_phase_meta",
    "windowed_selfplay_enabled",
    "make_command_decide_from_action_dict",
    "make_movement_decide_from_action_dict",
    "make_shooting_decide_from_action_dict",
    "make_charge_decide_from_action_dict",
    "make_fight_decide_from_action_dict",
    "run_model_command_from_action",
    "run_model_movement_from_action",
    "run_model_shooting_from_action",
    "run_model_charge_from_action",
    "run_model_fight_from_action",
    "run_model_turn_from_action",
    "command_replay_meta_from_action",
    "turn_replay_meta_from_action",
    "merge_command_meta_into",
    "merge_windowed_meta_into",
    "build_reaction_windows",
    "windowed_reaction_windows_enabled",
    "ActionKind",
    "ActionOption",
    "DecisionWindow",
    "Phase",
    "PhaseResult",
    "PhaseState",
    "PhaseTurnState",
    "SubStep",
    "Timing",
    "generate_windows",
    "command_window",
    "movement_options_for_unit",
    "shooting_options_for_unit",
    "charge_options_for_unit",
    "fight_stratagem_options_for_unit",
    "compile_options_to_action_dict",
    "default_action_dict",
    "StratagemDef",
    "Trigger",
    "UsageLimit",
    "REGISTRY",
    "by_id",
    "for_phase",
    "for_trigger",
    "legal_stratagem_options",
    "stratagem_engine",
    "apply_stratagem",
    "phase_engine",
]
